version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/incentive/api"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "axios"
      - dependency-name: "dotenv"
      - dependency-name: "express"
      - dependency-name: "joi"
      - dependency-name: "morgan"
      - dependency-name: "swagger-ui-express"
      - dependency-name: "lodash"
      - dependency-name: "minimatch"
      - dependency-name: "path-to-regexp"
      - dependency-name: "@types/express"
      - dependency-name: "@types/morgan"
      - dependency-name: "@types/node"
      - dependency-name: "@types/swagger-ui-express"
      - dependency-name: "ts-node"
      - dependency-name: "typescript"
  - package-ecosystem: "npm"
    directory: "/incentive/frontend"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "next"
      - dependency-name: "next-auth"
      - dependency-name: "react"
      - dependency-name: "react-dom"
      - dependency-name: "eslint-config-next"
      - dependency-name: "axios"
      - dependency-name: "minimatch"
      - dependency-name: "postcss"
  - package-ecosystem: "npm"
    directory: "/incentive/blockchain"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "hardhat"
      - dependency-name: "@nomicfoundation/hardhat-toolbox"
      - dependency-name: "@nomicfoundation/hardhat-ethers"
      - dependency-name: "@nomicfoundation/hardhat-chai-matchers"
      - dependency-name: "@nomicfoundation/hardhat-foundry"
      - dependency-name: "@nomicfoundation/hardhat-ignition"
      - dependency-name: "@nomicfoundation/hardhat-ignition-ethers"
      - dependency-name: "@nomicfoundation/hardhat-network-helpers"
      - dependency-name: "@nomicfoundation/hardhat-verify"
      - dependency-name: "@typechain/hardhat"
      - dependency-name: "@types/chai"
      - dependency-name: "@types/mocha"
      - dependency-name: "ts-node"
      - dependency-name: "typechain"
      - dependency-name: "ethers"
      - dependency-name: "serialize-javascript"
      - dependency-name: "undici"
      - dependency-name: "minimatch"
      - dependency-name: "picomatch"
      - dependency-name: "glob"
      - dependency-name: "lodash"
      - dependency-name: "lodash-es"
  - package-ecosystem: "yarn"
    directory: "/incentive/blockchain"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "hardhat"
      - dependency-name: "@nomicfoundation/hardhat-toolbox"
      - dependency-name: "@nomicfoundation/hardhat-ethers"
      - dependency-name: "@nomicfoundation/hardhat-chai-matchers"
      - dependency-name: "@nomicfoundation/hardhat-foundry"
      - dependency-name: "@nomicfoundation/hardhat-ignition"
      - dependency-name: "@nomicfoundation/hardhat-ignition-ethers"
      - dependency-name: "@nomicfoundation/hardhat-network-helpers"
      - dependency-name: "@nomicfoundation/hardhat-verify"
      - dependency-name: "@typechain/hardhat"
      - dependency-name: "@types/chai"
      - dependency-name: "@types/mocha"
      - dependency-name: "ts-node"
      - dependency-name: "typechain"
      - dependency-name: "ethers"
      - dependency-name: "serialize-javascript"
      - dependency-name: "undici"
      - dependency-name: "minimatch"
      - dependency-name: "picomatch"
      - dependency-name: "glob"
      - dependency-name: "lodash"
      - dependency-name: "lodash-es"
  - package-ecosystem: "yarn"
    directory: "/incentive/api"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "lodash"
      - dependency-name: "lodash-es"
      - dependency-name: "ethers"
      - dependency-name: "ts-node"
      - dependency-name: "typescript"
  - package-ecosystem: "yarn"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "hardhat"
      - dependency-name: "@nomicfoundation/hardhat-ethers"
      - dependency-name: "@types/chai"
      - dependency-name: "@types/mocha"
      - dependency-name: "chai"
      - dependency-name: "ethers"
      - dependency-name: "ts-node"
      - dependency-name: "typescript"
