version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/incentive/api"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "axios"
      - dependency-name: "dotenv"
      - dependency-name: "express"
      - dependency-name: "joi"
      - dependency-name: "morgan"
      - dependency-name: "swagger-ui-express"
      - dependency-name: "lodash"
      - dependency-name: "minimatch"
      - dependency-name: "path-to-regexp"
      - dependency-name: "@types/express"
      - dependency-name: "@types/morgan"
      - dependency-name: "@types/node"
      - dependency-name: "@types/swagger-ui-express"
      - dependency-name: "ts-node"
      - dependency-name: "typescript"
      - dependency-name: "uuid"
  - package-ecosystem: "npm"
    directory: "/incentive/frontend"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "next-auth"
        update-types:
          - "version-update:semver-major"
      - dependency-name: "react"
        update-types:
          - "version-update:semver-major"
      - dependency-name: "react-dom"
        update-types:
          - "version-update:semver-major"
      - dependency-name: "next"
        update-types:
          - "version-update:semver-major"
      - dependency-name: "eslint-config-next"
        update-types:
          - "version-update:semver-major"
      - dependency-name: "axios"
      - dependency-name: "minimatch"
      - dependency-name: "uuid"
      - dependency-name: "wagmi"
      - dependency-name: "@wagmi/connectors"
      - dependency-name: "@rainbow-me/rainbowkit"
      - dependency-name: "@metamask/sdk"
      - dependency-name: "@metamask/sdk-communication-layer"
      - dependency-name: "@metamask/rpc-errors"
      - dependency-name: "@metamask/utils"
      - dependency-name: "@gemini-wallet/core"
  - package-ecosystem: "yarn"
    directory: "/incentive/frontend"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "next-auth"
        update-types:
          - "version-update:semver-major"
      - dependency-name: "react"
        update-types:
          - "version-update:semver-major"
      - dependency-name: "react-dom"
        update-types:
          - "version-update:semver-major"
      - dependency-name: "next"
        update-types:
          - "version-update:semver-major"
      - dependency-name: "eslint-config-next"
        update-types:
          - "version-update:semver-major"
      - dependency-name: "axios"
      - dependency-name: "minimatch"
      - dependency-name: "uuid"
      - dependency-name: "wagmi"
      - dependency-name: "@wagmi/connectors"
      - dependency-name: "@rainbow-me/rainbowkit"
      - dependency-name: "@metamask/sdk"
      - dependency-name: "@metamask/sdk-communication-layer"
      - dependency-name: "@metamask/rpc-errors"
      - dependency-name: "@metamask/utils"
      - dependency-name: "@gemini-wallet/core"
  - package-ecosystem: "npm"
    directory: "/incentive/blockchain"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "hardhat"
      - dependency-name: "@nomicfoundation/hardhat-toolbox"
      - dependency-name: "@nomicfoundation/hardhat-ethers"
      - dependency-name: "@nomicfoundation/hardhat-chai-matchers"
      - dependency-name: "@nomicfoundation/hardhat-foundry"
      - dependency-name: "@nomicfoundation/hardhat-ignition"
      - dependency-name: "@nomicfoundation/hardhat-ignition-ethers"
      - dependency-name: "@nomicfoundation/hardhat-network-helpers"
      - dependency-name: "@nomicfoundation/hardhat-verify"
      - dependency-name: "@typechain/hardhat"
      - dependency-name: "@types/chai"
      - dependency-name: "@types/mocha"
      - dependency-name: "ts-node"
      - dependency-name: "typechain"
      - dependency-name: "ethers"
      - dependency-name: "serialize-javascript"
      - dependency-name: "undici"
      - dependency-name: "minimatch"
      - dependency-name: "picomatch"
      - dependency-name: "glob"
      - dependency-name: "lodash"
      - dependency-name: "lodash-es"
      - dependency-name: "uuid"
      - dependency-name: "solidity-coverage"
      - dependency-name: "hardhat-gas-reporter"
      - dependency-name: "bn.js"
      - dependency-name: "js-yaml"
      - dependency-name: "ethjs-unit"
      - dependency-name: "sc-istanbul"
      - dependency-name: "web3-utils"
      - dependency-name: "number-to-bn"
      - dependency-name: "secp256k1"
      - dependency-name: "ethereum-cryptography"
      - dependency-name: "ethereumjs-util"
      - dependency-name: "@sentry/node"
      - dependency-name: "cookie"
      - dependency-name: "@ethersproject/abi"
      - dependency-name: "@ethersproject/abstract-provider"
      - dependency-name: "@ethersproject/abstract-signer"
      - dependency-name: "@ethersproject/hash"
      - dependency-name: "@ethersproject/signing-key"
      - dependency-name: "@ethersproject/transactions"
  - package-ecosystem: "yarn"
    directory: "/incentive/blockchain"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "hardhat"
      - dependency-name: "@nomicfoundation/hardhat-toolbox"
      - dependency-name: "@nomicfoundation/hardhat-ethers"
      - dependency-name: "@nomicfoundation/hardhat-chai-matchers"
      - dependency-name: "@nomicfoundation/hardhat-foundry"
      - dependency-name: "@nomicfoundation/hardhat-ignition"
      - dependency-name: "@nomicfoundation/hardhat-ignition-ethers"
      - dependency-name: "@nomicfoundation/hardhat-network-helpers"
      - dependency-name: "@nomicfoundation/hardhat-verify"
      - dependency-name: "@typechain/hardhat"
      - dependency-name: "@types/chai"
      - dependency-name: "@types/mocha"
      - dependency-name: "ts-node"
      - dependency-name: "typechain"
      - dependency-name: "ethers"
      - dependency-name: "serialize-javascript"
      - dependency-name: "undici"
      - dependency-name: "minimatch"
      - dependency-name: "picomatch"
      - dependency-name: "glob"
      - dependency-name: "lodash"
      - dependency-name: "lodash-es"
      - dependency-name: "uuid"
      - dependency-name: "solidity-coverage"
      - dependency-name: "hardhat-gas-reporter"
      - dependency-name: "bn.js"
      - dependency-name: "js-yaml"
      - dependency-name: "ethjs-unit"
      - dependency-name: "sc-istanbul"
      - dependency-name: "web3-utils"
      - dependency-name: "number-to-bn"
      - dependency-name: "secp256k1"
      - dependency-name: "ethereum-cryptography"
      - dependency-name: "ethereumjs-util"
      - dependency-name: "@sentry/node"
      - dependency-name: "cookie"
      - dependency-name: "@ethersproject/abi"
      - dependency-name: "@ethersproject/abstract-provider"
      - dependency-name: "@ethersproject/abstract-signer"
      - dependency-name: "@ethersproject/hash"
      - dependency-name: "@ethersproject/signing-key"
      - dependency-name: "@ethersproject/transactions"
  - package-ecosystem: "yarn"
    directory: "/incentive/api"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "lodash"
      - dependency-name: "lodash-es"
      - dependency-name: "ethers"
      - dependency-name: "ts-node"
      - dependency-name: "typescript"
      - dependency-name: "uuid"
  - package-ecosystem: "yarn"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "hardhat"
      - dependency-name: "@nomicfoundation/hardhat-ethers"
      - dependency-name: "@types/chai"
      - dependency-name: "@types/mocha"
      - dependency-name: "chai"
      - dependency-name: "ethers"
      - dependency-name: "ts-node"
      - dependency-name: "typescript"
      - dependency-name: "serialize-javascript"
      - dependency-name: "path-to-regexp"
      - dependency-name: "minimatch"
      - dependency-name: "undici"
      - dependency-name: "picomatch"
      - dependency-name: "bn.js"
      - dependency-name: "cookie"
      - dependency-name: "tmp"
      - dependency-name: "elliptic"
      - dependency-name: "uuid"
