version: "3"

services:
  core-frontend:
    build:
      context: ./app
      dockerfile: Dockerfile.frontend
    environment:
      - REACT_APP_ENVIRONMENT=production
      - REACT_APP_BASE_URL_PROD=http://localhost:3001/
      - REACT_APP_BASE_URL_DEV=http://localhost:9081/
    ports:
      - "3000:80" # http://localhost:3000
    depends_on:
      - core-api
    networks:
      - core-network

  core-api:
    build:
      context: ./app
      dockerfile: Dockerfile.server
    ports:
      - "3001:9081" # http:localhost:3001
    environment:
      MONGODB_URI: "mongodb://mongodb:27017/jsonldDB"
    depends_on:
      - mongodb
    networks:
      - core-network

  incentive-api:
    build:
      context: .
      dockerfile: incentive/api/Dockerfile
    ports:
      - "3002:3000" # http://localhost:3002
    environment:
      PORT: 3000
      PRIVATE_KEY: "0xdf57089febbacf7ba0bc227dafbffa9fc08a93fdc68e1e42411a14efcf23656e"
      RPC_URL: http://localhost:8545
    depends_on:
      - hardhat

  incentive-frontend:
    build:
      context: ./incentive/frontend
      dockerfile: Dockerfile
    ports:
      - "3003:3000" # http://localhost:3003
    depends_on:
      - hardhat

  incenti-trace:
    build:
      dockerfile: Dockerfile.server
      context: ./
    environment:
      - ENVIRONMENT=production
    command: ["node", "./execute-incenti-trace.js"]
    ports:
      - "3005:9091" # http:localhost:3004
    depends_on:
      - core-api
    networks:
      - core-network
    
  engine-test:
    build:
      dockerfile: Dockerfile.server
      context: ./
    environment:
      - ENVIRONMENT=production
    command: ["node", "./core-engine.js"]
    ports:
      - "3004:9091" # http:localhost:3004
    depends_on:
      - core-api
    networks:
      - core-network
    

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - core-network

  hardhat:
    build:
      context: ./incentive/blockchain
      dockerfile: Dockerfile
    ports:
      - "8545:8545"

networks:
  core-network:
    driver: bridge

volumes:
  mongo_data:
