version: "3"

services:
  core-frontend:
    build:
      context: ./app
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:80" # http://localhost:3000
    depends_on: 
      - core-api
    networks:
      - core-network

  core-api:
    build:
      context: ./app
      dockerfile: Dockerfile.server
    ports:
      - "3001:9081" # http:localhost:3001
    environment:
      MONGODB_URI: "mongodb://mongodb:27017/jsonldDB"
    depends_on:
      - mongodb
    networks:
      - core-network

  incentive-api:
    build:
      context: ./incentive/api
      dockerfile: Dockerfile
    ports:
      - "3002:3000" # http://localhost:3002
    environment:
      PORT: 3000
    depends_on:
      - hardhat

  incentive-frontend:
    build:
      context: ./incentive/frontend
      dockerfile: Dockerfile
    ports:
      - "3003:3000" # http://localhost:3003
    depends_on:
      - hardhat

  incenti-trace:
    build:
      dockerfile: Dockerfile.server
    ports:
      - "3004:9091" # http:localhost:3004
    depends_on:
      - core-api
    networks:
      - core-network  

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - core-network

  hardhat:
    build:
      context: ./incentive/blockchain
      dockerfile: Dockerfile
    ports:
      - "8545:8545"

networks:
  core-network:
    driver: bridge  

volumes:
  mongo_data:
